parser: "@typescript-eslint/parser"

parserOptions:
  project:
    - 'tsconfig.json'
    - 'tsconfig.test.json'
  tsconfigRootDir: '.'

plugins:
  - "@typescript-eslint"
  - prettier
  - standard
  - jest

extends:
  - standard
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier

rules:
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-unused-vars": off
  "@typescript-eslint/no-var-requires": off

env:
  jest/globals: true
  node: true
