image: node:alpine

stages:
  - install
  - test

install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules 
  cache:
    paths:
      - node_modules

lint:
  stage: test
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm run test
