version: 2.1

executors:
  worker:
    docker:
      - image: circleci/node
    working_directory: ~/ci

jobs:
  install:
    executor: worker
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}
          - node_modules-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "package.json" }}

  test:
    executor: worker
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run test

  build:
    executor: worker
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}
      - run: npm run build
      - persist_to_workspace:
          root: ~/ci
          paths: .

  publish:
    executor: worker
    steps:
      - add_ssh_keys:
          fingerprints:
            - "56:d9:f4:6f:c5:58:f8:a1:29:a5:0e:18:f3:b6:59:56"
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - attach_workspace:
          at: ~/ci
      - run: git config user.email "$GIT_AUTHOR_EMAIL"
      - run: git config user.name "$GIT_AUTHOR_NAME"
      - run: npm run version
      - run: git push --follow-tags origin master
      - run: npm config set "//registry.npmjs.org/:_authToken" "$NPM_TOKEN"
      - deploy: 
          command: npm publish

workflows:
  version: 2
  ci:
    jobs:
      - install:
          filters:
            branches:
              ignore:
                - /^chore\(release\).*/
      - test:
          requires:
            - install
      - build:
          requires:
            - install
      - publish:
          requires:
            - test
            - build
          context: npm token
